require 'puppetx/filemapper'
require 'puppet/util/parslets/crontab'

Puppet::Type.type(:cron).provide(:parslet) do
  include PuppetX::FileMapper

  desc 'Prototype crontab manager'

  def select_file
    # NOTE: In order to be *completely* compatible with the crontab provider,
    # we should also fall back to the target property ...but I currently
    # believe that property needs to go die in a fire.
    user
  end

  def self.target_files
    # FIXME: This works on CentOS. For a more complete list of crontab
    # locations, see the following PR:
    #
    #   https://github.com/puppetlabs/puppet/pull/2136/files#diff-7d6c86785382e05c0252055af2efa381R97
    Pathname.glob('/var/spool/cron/*').map {|p| p.basename.to_s}
  end

  def self.parse_file(filename, contents)
    records = CrontabTransformer.new.apply(CrontabParser.new.parse(contents))

    records.each do |h|
      h[:user] = filename
      h[:target] = filename # Don't ever touch this. Just use user.
      if h[:name].is_a? Hash
        # This means the parser didn't find a Puppet Name for the cron job and
        # stored the line number in the :line entry of a Hash. Make a name up.
        h[:name] = "Unmanaged Job (#{filename}:line #{h[:name][:line]})"
      end
    end

    records
  end

  # A bit hacky. Assumes that all properties will be assigned the value of
  # :absent if not specified in the resource definition.
  #
  # FIXME: Don't assign Puppet Names to unmanaged jobs.
  def self.format_file(filename, providers)
    content = header
    content += providers.reject{|p| p.ensure == :absent}.map do |p|
      entry = ''
      entry += "# Puppet Name: #{p.name}\n"
      entry += (p.environment.join("\n") + "\n") unless p.environment == :absent
      entry += if p.special != :absent
        "#{p.special} "
      else
        [:minute, :hour, :monthday, :month, :weekday].map do |k|
          if p.send(k) == :absent
            '*'
          else
            p.send(k).join(',')
          end
        end.join(' ')
      end

      entry += " #{p.command}\n"

      entry
    end.join

    content
  end

 def self.header
    str = <<-HEADER
# HEADER: This file was autogenerated at #{Time.now} by puppet.
# HEADER: While it can still be managed manually, it is definitely not recommended.
# HEADER: Note particularly that the comments starting with 'Puppet Name' should
# HEADER: not be deleted, as doing so could cause duplicate cron jobs.
HEADER
    str
 end

end
